# Indicate the subfolder of the input folder that contains the input files
filepaths:
  "sector_table": "Network/sector_table.csv"
  "inventory_duration_targets": "Network/inventory_targets.csv"
  "mrio": "Network/figaro_2023_agg.csv"
  "region_table": "Network/region_table.geojson"
  "usd_per_ton": "Network/usd_per_ton.csv"
transport_modes: [roads, maritime] #, waterways, airways]
monetary_units_in_model: mUSD
monetary_units_inputed: mUSD
time_resolution: week
io_cutoff: 0.01
simulation_type: disruption
export_files: True
export_details:
  "flows": True
firm_data_type: "mrio"
nb_suppliers_per_input: 1
#adapt_weight_based_on_satisfaction: True
stream_mode: "loss_only"

inventory_duration_targets:
  definition: per_input_type  # inputed
  values:
    default: 30
    food: 5
    mining: 30
    utility: 3
    agriculture: 15
    manufacturing: 30
    service: 90
    trade: 30
    transport: 5
  unit: day

with_transport: False

disruption_description: None
t_final: 26
#disruptions:
#- attribute: id
#  description_type: edge_attributes
#  duration: 7
#  start_time: 1
#  type: transport_disruption
#  values:
#  - 13216
#  - 15827
#  - 12055
disruptions:
  - type: export_stop
    start_time: 1
    duration: 8
    #description_type: region_sector_file
    description_type: filter  # sectors_homogeneous
    filter:
      region_sector: ['CN_C26', 'CN_C27', 'CN_C28']
#      sector: ['C16']
#    destroyed_capital: 3321980.0
#    unit: mUSD
    reconstruction_market: False
#  - type: transport_disruption
#    description_type: edge_attributes
#    attribute: id
#    values: [13216, 15827, 12055]
#    start_time: 1
#    duration: 7
