# Indicate the subfolder of the input folder that contains the input files
filepaths:
  "sector_table": "Network/sector_table_g.csv"
  #"inventory_duration_targets": "Network/inventory_targets.csv"
  "mrio": "Network/mrio_va_fd.pkl"
  #"region_table": "Network/region_table.geojson"
  "usd_per_ton": "Network/USD_per_ton.csv"
transport_modes: [roads, maritime] #, waterways, airways]
monetary_units_in_model: kUSD
monetary_units_inputed: kUSD
time_resolution: week
epsilon_stop_condition: 1e-3

io_cutoff: 0.0001

# Filter out sectors whose output is below that cutoff value
# - if 'type' is 'percentage', test cutoff against the sector's relative output
# - if 'type' is 'absolute', test cutoff against the sector's absolute output
# - if 'type' is 'relative_to_average', the cutoff is (cutoff value) * (country's total output) / (nb sectors)
cutoff_sector_output:
  'type': 'absolute'
  'value': 1.0
  'unit': 'mUSD'

cutoff_sector_demand:
  'type': 'absolute'
  'value': 1.0
  'unit': 'mUSD'

# Filter out sectors firms output is below that cutoff value
cutoff_firm_output:
  'type': 'absolute'
  'value': 10
  "unit": "kUSD"

# Filter out region_sector to households links if purchase is below that cutoff value
cutoff_household_demand:
  'type': 'absolute'  # only absolute works
  'value': 10
  "unit": "kUSD"

inventory_duration_targets:
  definition: per_input_type  # inputed
  values:
    default: 30 # - old 30
    food: 20 #20 doh, 36.5 IT
    mining: 30 #24 days - old 30
    utility: 3 #industry turnover 24-50 days, but then used immediately? - old 3
    agriculture: 20 #20 DOH, IT 43 - old 15
    manufacturing: 40 #60 DOH, Inventory Turnover 47-52 - old 30
    service: 90 #9 Inventory Turnover 9-15days, but non-essential input
    trade: 40 #old 30
    transport: 5 #Inventory turnover for trucking 2 days, maritime 30 days - old 5  

  unit: day

#    default: 50 #50 - old 30
#    food: 20 #20 doh, 36.5 IT - old 5
#    mining: 24 #24 days - old 30
#    utility: 30 #industry turnover 24-50 days, but then used immediately? - old 3
#    agriculture: 20 #20 DOH, IT 43 - old 15
#    manufacturing: 60 #60 DOH, Inventory Turnover 47-52 - old 30
#    service: 12 #9 Inventory Turnover 9-15days, but do they care if the services are gone? - old 90
#    trade: 60 # 60 - old 30
#    transport: 5 #Inventory turnover for trucking 2 days, maritime 30 days - old 5
#    #construction: 17

simulation_type: disruption
export_files: True
export_details:
  "flows": True
firm_data_type: "mrio"
with_transport: False
#parallelized: False             # Enable parallel route calculation
#max_workers: 10                 # Number of parallel workers
stream_mode: "loss_only"

disruption_description: None
t_final: 26

disruptions:
  - type: export_stop
    start_time: 1
    duration: 12
#    description_type: region_sector_file
    description_type: filter  # sectors_homogeneous
    filter:
      region_sector: ['IDN_Nickel ores', 'IDN_Basic nickel']
      #region: ['']
    #destroyed_capital: 4.0
#    region_sector_filepath: "Disruption/earthquake_capital_destruction.csv"
    #unit: mUSD
    reconstruction_market: False

#disruption_description:
#  type: compound
#  events:
#    - item_type: transport_edges
#      attribute: id
#      values: [465]
#      start_time: 1
#      duration: 1
