# Indicate the subfolder of the input folder that contains the input files
filepaths:
  "sector_table": "Network/sector_table.csv"
  "inventory_duration_targets": "Network/inventory_targets.csv"
  "mrio": "Network/figaro_2023_agg.csv"
  "region_table": "Network/region_table.geojson"
  "usd_per_ton": "Network/usd_per_ton.csv"
transport_modes: [roads, maritime] #, waterways, airways]
monetary_units_in_model: mUSD
monetary_units_inputed: mUSD
time_resolution: day
io_cutoff: 0.01
simulation_type: disruption
export_files: True
export_details:
  "flows": True
firm_data_type: "mrio"

with_transport: False

disruption_description: None
t_final: 4

disruptions:
  - type: capital_destruction
    start_time: 1
    description_type: region_sector_file
    description_type: filter  # sectors_homogeneous
    filter:
      sector: ['C16']
    destroyed_capital: 332198.0
    unit: mUSD
    reconstruction_market: False
#  - type: transport_disruption
#    description_type: edge_attributes
#    attribute: id
#    values: [13216, 15827, 12055]
#    start_time: 1
#    duration: 7
